spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/backspace
    username: milkman
    password: Milkman64
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true